[tox]
isolated_build = true
env_list = py{39,310,311,312}

[testenv]
skip_install = true
allowlist_externals = make
commands_pre = poetry install --without build
commands = make test

[flake8]
ignore = E501,C901
max-line-length = 1000
exclude = tests/*
max-complexity = 10